name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token:      ${{ secrets.WIKI_PAT }}
          path:       wiki
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: true
          chart: true
          amend: true